In [14]:
import numpy as np
import numpy.linalg as lin
print(np.version.full_version)
from scipy import linalg
import sol

1.16.4


## Lebegőpontos számok
$$
x=\pm 2^k \left(1+\frac{x_1}{2}+\frac{x_2}{2^2}+\ldots+\frac{x_t}{2^t} \right)\ \ \ x_i \in \{0,1\}
$$
ahol $k_- \le k \le k_+$ és $t>0$ egész számok a rendszer paraméterei.

### Konstansok

$$ 
\varepsilon_{0}=2^{k_{-}} 
$$



$$ 
M_{\infty}=2^{k_{+}}\left(2-\frac{1}{2^t}\right) 
$$


$$ 
\varepsilon_1 = 2^{-t}
$$

Az 64-bites lebegőpontos számoknál (double precision): $ 1,11,52 $ bit van az előjelre, a $k_{-},k_{+}$-nak megfelelő tartományra illetve a jegyekre ($x_i$) $\hskip 0.5cm$
Bővebben: [wiki-double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)


### Relatív hiba
Legyen $x=2^k 1.x_1\ldots x_t x_{t+1}\ldots$
$$ 
\frac{| x-fl(x)|}{|x|}\le \frac{2^{k-t-1}}{|x|}\le \frac{2^{k-t-1}}{2^k}=\frac{\varepsilon_1}{2} 
$$
ha a közelebbi lebegőpontos számhoz kerekít a gép. 

In [7]:
info=np.finfo(np.float64)
print(info.nexp,info.nmant)
#legkisebb
print(info.tiny,info.tiny==2**-1022)
# legnagyobb
print(info.max,info.max==2**1023*(2-1/2**52))
# 1 és a jobboldali szomszedja tavolsaga
print(info.eps,info.eps==2**(-52))


11 52
2.2250738585072014e-308 True
1.7976931348623157e+308 True
2.220446049250313e-16 True


### Feladat
1. Határozd meg kísérletileg az $\varepsilon_1$ értékét!
1. Határozd meg kísérletileg az $\varepsilon_0$ értékét!


## Norma
Jele $\Vert x\Vert$ (iksznorma). 

### Tulajdonságok:
1. $\Vert x\Vert \ge 0$, 
1. $\Vert x\Vert =0 \iff x=0$
1. $\Vert \alpha x\Vert =|\alpha| \Vert x\Vert $
1. $\Vert x+y\Vert \le \Vert x\Vert +\Vert y\Vert $ 
<br>

### Példák:

1. $\Vert x\Vert_{1}=\sum |x_k|$
1. $\Vert x\Vert_{2}=\sqrt{\sum |x_k|^2}$
1. $\Vert x\Vert_{\infty}=\max |x_k|$

### Feladat:
1. Írjunk egy olyan függvényt mely kiszámolja egy paraméterül kapott vektor fenti normáit.

### Négyzetes mátrixok normája:
Legyen $\Vert.\Vert_v$ egy vektornorma. Ekkor:

$$
\Vert A\Vert_v=\sup_{x\neq 0}\frac{\Vert Ax\Vert_v}{\Vert x\Vert_v}
=\max_{x\neq 0}\frac{\Vert Ax\Vert_v}{\Vert x\Vert_v}=\max_{\Vert x\Vert_v=1}\Vert Ax\Vert_v
$$

1. Ez a $\Vert.\Vert_v$ által indukált mátrixnorma.
1. $\Vert E\Vert=1$
1. $\Vert AB\Vert\le \Vert A\Vert \Vert B\Vert$
A:

### Számolási szabályok mátrixnormára:

1. $\Vert A\Vert_1=\max_j \sum_i a_{ij}$
1. $\Vert A\Vert_{\infty}=\max_i \sum_j a_{ij}$
1. $\Vert A\Vert_2=\sqrt{\lambda_{max}(A^T A)}$

### Feladat
1. Írjunk egy függvényt mely kiszámolja egy paraméterül kapott mátrix $1$ és $\infty$ normáját:

In [8]:
for A in ([[1,2],[3,4]], [[0,-2,1],[11,-3,4],[6,-2,2]]):
    print(sol.matrixnorma(A))

(6, 7)
(17, 18)


### Hiba a lineáris egyenletrendszer jobboldalában - kondíciószám
\begin{gather}
Ax =b \\
A(x+\delta x)=b+\delta b \ \ \implies \\
\frac{\frac{\Vert \delta x\Vert}{\Vert x\Vert}}{\frac{\Vert \delta b\Vert}{\Vert b\Vert}} =
\frac{\Vert A^{-1}(\delta b)\Vert }{\Vert\delta b\Vert} \frac{\Vert Ax\Vert }{\Vert x\Vert}\le 
\Vert A^{-1}\Vert \Vert A\Vert=cond(A)
\end{gather}

A kondíciószám: hányszoros szorzóval jelenhet meg a jobboldal hibája a megoldásban. (legrosszabb eset)


### Feladat
Oldjuk meg "kézzel" az alábbi egyenletrendszereket - hasonlítsuk össze a megoldásokat. Számoljuk ki a mátrix kondíciószámát.
$$
\begin{bmatrix}
1\ \ 1 \\
1\ 1.0001
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix} =
\begin{bmatrix}
2 \\
2
\end{bmatrix}
$$
$$
\begin{bmatrix}
1\ \ 1 \\
1\ 1.0001
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix} =
\begin{bmatrix}
2 \\
2.0001
\end{bmatrix}
$$

Megoldás numpy-val:

In [9]:
A=np.array([[1,1],[1,1.0001]])
b0=np.array([2,2])
b1=np.array([2,2.0001])
x0=lin.solve(A,b0)
x1=lin.solve(A,b1)
print('x0=',x0,'x1=',x1)
relhx=lin.norm(x0-x1,1)/lin.norm(x0,1)
relhb=lin.norm(b0-b1,1)/lin.norm(b0,1)
változás=relhx/relhb
print(változás,lin.cond(A,1))

x0= [2. 0.] x1= [1. 1.]
40000.0000000044 40004.0001000044


## LU-felbontás

Lineáris egyenletrendszer megoldását visszavezethetjük egyváltozós egyenletek megoldásának sorozatára. Ehhez a rendszert fokozatosan egyszerűsítjük, bizonyos egyenletekből kiküszöbölünk bizonyos változókat. Ez a Gauss-elimináció.

### Bővebben: [lineáris egyenletrendszerek](https://arato.inf.unideb.hu/noszaly.csaba/numen/2019/03_sle/03_sle.pdf)

### Feladat:
Írjunk egy függvényt mely egy paraméterül kapott mátrix $LU$ felbontását adja vissza, ha létezik egyébként ```None```-t 

In [15]:
for A in ([[1,2],[3,4]], [[1,-2,1],[11,-3,4],[6,-2,2]]):
    print(sol.lu(A), linalg.lu(A))
    

[[ 1  2]
 [ 3 -2]] (array([[0., 1.],
       [1., 0.]]), array([[1.        , 0.        ],
       [0.33333333, 1.        ]]), array([[3.        , 4.        ],
       [0.        , 0.66666667]]))
[[ 1 -2  1]
 [11 19 -7]
 [ 6  0 -4]] (array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]), array([[1.        , 0.        , 0.        ],
       [0.09090909, 1.        , 0.        ],
       [0.54545455, 0.21052632, 1.        ]]), array([[11.        , -3.        ,  4.        ],
       [ 0.        , -1.72727273,  0.63636364],
       [ 0.        ,  0.        , -0.31578947]]))


## Cholesky-felbontás

Ha a mátrix speciális pl. szimmetrikus vagy egyéb rendezettséget mutat akkor amint várható speciális algoritmusokkal lehet megoldani a kapcsolódó egyenletrendszert.
Legyen $A$ egy szimmetrikus pozitív definit mátrix. Ekkor létezik egy $Q$ alsó-háromszög mátrix, mellyel $A=QQ^T$. Ez a Cholesky-felbontás.